name: StayFlow CI
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  REGISTRY: "lashkapashka"
  IMAGE_NAME: "crud-server"

jobs:
  image-build-and-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - image: booking
            service: BookingService
          - image: hotel
            service: HotelService
          - image: payment
            service: PaymentService

    steps:
      - name: Checkout master
        uses: actions/checkout@v5
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to Docker Registry
        run: docker login -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }}
      
      - name: Build and Push Docker Image
        run: |
          TAG_NAME=$(echo $GITHUB_SHA | head -c7)
          FULL_IMAGE_NAME=$REGISTRY/${{ matrix.image }}_img

          echo "Building $FULL_IMAGE_NAME:$TAG_NAME"

          docker buildx create --use
          docker buildx build \
            -t $FULL_IMAGE_NAME:$TAG_NAME \
            -t $FULL_IMAGE_NAME:latest \
            -f ./${{ matrix.service }}/Dockerfile ./${{ matrix.service }} \
            --push
  # deploy-image:
  #   runs-on: ubuntu-latest
  #   needs: image-build-and-push

  #   steps:
  #     - name: Deploy to Server via SSH action
  #       uses: appleboy/ssh-action@v1.0.0
  #       with:
  #         host: ""
  #         username: ""
  #         key: ""
  #         envs: ""
  #         scripts: |
            